//! JS shim template generation.
//!
//! Produces a self-contained `JavaScript` file that:
//! 1. Defines host function wrappers (lazy-resolved, not called during Wizer init)
//! 2. Wraps the original plugin code in an IIFE with CJS module simulation
//! 3. Provides an `OpenClaw` context mock that maps to Astrid host functions
//! 4. Exports `describe-tools`, `execute-tool`, and `run-hook` for the Extism runtime
//!
//! Host functions are NOT available during Wizer pre-initialization. All host
//! function calls (config loading, plugin activation, logging) are deferred to
//! the first runtime export invocation via `_ensureActivated()`.

use std::collections::HashMap;

/// Plugin identity fields extracted from the manifest, baked into the shim
/// so the plugin code can access `context.id`, `context.name`, etc.
#[derive(Debug, Default)]
pub struct PluginIdentity<'a> {
    /// Plugin identifier (e.g. `"my-tool"`).
    pub id: &'a str,
    /// Optional human-readable name.
    pub name: Option<&'a str>,
    /// Optional semantic version string.
    pub version: Option<&'a str>,
    /// Optional description.
    pub description: Option<&'a str>,
}

/// Generate the complete JS shim wrapping the given plugin code.
///
/// `plugin_code` should be the bundled CJS output from esbuild (or raw JS if `--skip-bundle`).
/// `config` is the set of config key-value pairs to bake into the shim.
/// `identity` provides manifest-sourced plugin identity for the context object.
#[must_use]
#[expect(clippy::implicit_hasher)]
pub fn generate(
    plugin_code: &str,
    config: &HashMap<String, serde_json::Value>,
    identity: &PluginIdentity<'_>,
) -> String {
    let config_keys = generate_config_keys(config);
    let header = generate_header(&config_keys, identity);
    let exports = generate_exports();
    format!(
        "{header}\n// --- BEGIN PLUGIN CODE ---\n{plugin_code}\n  // --- END PLUGIN CODE ---\n  return module.exports.default || module.exports;\n}})();\n\n{exports}"
    )
}

/// Generate the shim header: host function wrappers, context mock, and IIFE open.
///
/// No host functions are called at the top level — everything is deferred.
#[expect(clippy::too_many_lines)]
fn generate_header(config_keys: &str, identity: &PluginIdentity<'_>) -> String {
    let node_polyfills = generate_node_polyfills();
    let plugin_id = escape_js_string(identity.id);
    let plugin_name = identity.name.map_or_else(
        || "null".to_string(),
        |n| format!("\"{}\"", escape_js_string(n)),
    );
    let plugin_version = identity.version.map_or_else(
        || "\"0.0.0\"".to_string(),
        |v| format!("\"{}\"", escape_js_string(v)),
    );
    let plugin_description = identity.description.map_or_else(
        || "null".to_string(),
        |d| format!("\"{}\"", escape_js_string(d)),
    );
    format!(
        r#"// Generated by astrid-openclaw — do not edit.
// Plugin WASM shim.
//
// IMPORTANT: No host function calls during init (Wizer snapshot phase).
// All host calls are deferred to _ensureActivated(), called on first export.

// ── Host function imports (lazy — resolved on first call, not during Wizer init) ──
var _Host = Host;
var _hostFns = null;

function _getHostFn(name) {{
  if (!_hostFns) {{
    _hostFns = _Host.getFunctions();
  }}
  return _hostFns[name];
}}

// ── Memory helpers ─────────────────────────────────────────────────
function _toMem(s) {{
  return Memory.fromString(String(s));
}}

function _fromMem(offset) {{
  var m = Memory.find(offset);
  if (!m) return "";
  return m.readString();
}}

// ── Host function wrappers ─────────────────────────────────────────
function hostLog(level, msg) {{
  var lm = _toMem(level);
  var mm = _toMem(msg);
  _getHostFn("astrid_log")(lm.offset, mm.offset);
}}

function hostGetConfig(key) {{
  var km = _toMem(key);
  var result = _getHostFn("astrid_get_config")(km.offset);
  return _fromMem(result);
}}

function hostReadFile(path) {{
  var pm = _toMem(path);
  var result = _getHostFn("astrid_read_file")(pm.offset);
  return _fromMem(result);
}}

function hostWriteFile(path, content) {{
  var pm = _toMem(path);
  var cm = _toMem(content);
  _getHostFn("astrid_write_file")(pm.offset, cm.offset);
}}

function hostKvGet(key) {{
  var km = _toMem(key);
  var result = _getHostFn("astrid_kv_get")(km.offset);
  return _fromMem(result);
}}

function hostKvSet(key, value) {{
  var km = _toMem(key);
  var vm = _toMem(value);
  _getHostFn("astrid_kv_set")(km.offset, vm.offset);
}}

function hostHttpRequest(requestJson) {{
  var rm = _toMem(requestJson);
  var result = _getHostFn("astrid_http_request")(rm.offset);
  return _fromMem(result);
}}

function hostFsExists(path) {{
  var pm = _toMem(path);
  var result = _getHostFn("astrid_fs_exists")(pm.offset);
  return _fromMem(result) === "true";
}}

function hostFsMkdir(path) {{
  var pm = _toMem(path);
  _getHostFn("astrid_fs_mkdir")(pm.offset);
}}

function hostFsReaddir(path) {{
  var pm = _toMem(path);
  var result = _getHostFn("astrid_fs_readdir")(pm.offset);
  return JSON.parse(_fromMem(result));
}}

function hostFsStat(path) {{
  var pm = _toMem(path);
  var result = _getHostFn("astrid_fs_stat")(pm.offset);
  return JSON.parse(_fromMem(result));
}}

function hostFsUnlink(path) {{
  var pm = _toMem(path);
  _getHostFn("astrid_fs_unlink")(pm.offset);
}}

{node_polyfills}

// ── Host function metadata (needed by Host.getFunctions()) ──────────
// Sorted alphabetically by name — indices must match shim dispatch order.
// `results`: 1 = returns a value, 0 = void.
Host.__hostFunctions = [
  {{ name: "astrid_fs_exists", results: 1 }},
  {{ name: "astrid_fs_mkdir", results: 0 }},
  {{ name: "astrid_fs_readdir", results: 1 }},
  {{ name: "astrid_fs_stat", results: 1 }},
  {{ name: "astrid_fs_unlink", results: 0 }},
  {{ name: "astrid_get_config", results: 1 }},
  {{ name: "astrid_http_request", results: 1 }},
  {{ name: "astrid_kv_get", results: 1 }},
  {{ name: "astrid_kv_set", results: 0 }},
  {{ name: "astrid_log", results: 0 }},
  {{ name: "astrid_read_file", results: 1 }},
  {{ name: "astrid_write_file", results: 0 }}
];

// ── Config keys (baked at generation time, loaded lazily at runtime) ──
var _CONFIG_KEYS = [{config_keys}];

// ── Tool registry ──────────────────────────────────────────────────
var _registeredTools = {{}};

// ── Service, channel, hook, event, and metadata registries ─────────
var _registeredServices = {{}};
var _registeredChannels = {{}};
var _registeredHooks = {{}};
var _eventHandlers = {{}};
var _registeredMetadata = {{
  commands: {{}},
  gatewayMethods: {{}},
  httpHandlers: [],
  httpRoutes: [],
  providers: {{}},
  cliCommands: {{}}
}};

// ── Plugin config (populated lazily by _ensureActivated) ───────────
var _pluginConfig = {{}};

// ── Plugin context ─────────────────────────────────────────────────
var _openclawContext = {{
  // Plugin identity (from manifest)
  id: "{plugin_id}",
  name: {plugin_name},
  version: {plugin_version},
  description: {plugin_description},
  source: "wasm",

  // Config (populated at activation)
  config: _pluginConfig,
  pluginConfig: _pluginConfig,

  // Logger
  logger: {{
    info: function(msg) {{ hostLog("info", msg); }},
    warn: function(msg) {{ hostLog("warn", msg); }},
    error: function(msg) {{ hostLog("error", msg); }},
    debug: function(msg) {{ hostLog("debug", msg); }}
  }},

  // Workspace root
  workspace: ".",

  // Path resolution helper
  resolvePath: function() {{
    var parts = Array.prototype.slice.call(arguments);
    return parts.join("/").replace(/\/+/g, "/");
  }},

  // ── 1 & 2. registerTool (string name + object definition forms) ──
  registerTool: function(nameOrDef, definitionOrHandler, maybeHandler) {{
    var toolName, definition, handler;
    if (typeof nameOrDef === "string") {{
      toolName = nameOrDef;
      definition = definitionOrHandler;
      handler = maybeHandler;
    }} else {{
      toolName = nameOrDef.name;
      definition = nameOrDef;
      handler = definitionOrHandler;
    }}
    _registeredTools[toolName] = {{
      name: toolName,
      definition: definition,
      handler: handler
    }};
  }},

  // ── 3. registerService ────────────────────────────────────────────
  registerService: function(name, service) {{
    _registeredServices[name] = service;
    hostLog("debug", "registered service: " + name);
  }},

  // ── 4 & 5. registerChannel (string name + object definition forms) ─
  registerChannel: function(nameOrDef, definitionOrHandler, maybeHandler) {{
    var channelName, definition, handler;
    if (typeof nameOrDef === "string") {{
      channelName = nameOrDef;
      definition = definitionOrHandler || {{}};
      handler = maybeHandler;
    }} else {{
      channelName = nameOrDef.name;
      definition = nameOrDef;
      handler = definitionOrHandler;
    }}
    _registeredChannels[channelName] = {{
      name: channelName,
      definition: definition,
      handler: handler
    }};
    hostLog("debug", "registered channel: " + channelName);
  }},

  // ── 6. registerHook ───────────────────────────────────────────────
  registerHook: function(hookName, handler) {{
    if (!_registeredHooks[hookName]) _registeredHooks[hookName] = [];
    _registeredHooks[hookName].push(handler);
  }},

  // ── 7. registerCommand → mapped to tool with "cmd:" prefix ───────
  registerCommand: function(name, handler) {{
    var toolName = "cmd:" + name;
    _registeredTools[toolName] = {{
      name: toolName,
      definition: {{ description: "Command: " + name, inputSchema: {{ type: "object", properties: {{}} }} }},
      handler: function(id, params) {{
        var result = typeof handler === "function" ? handler(params) : handler.handler(params);
        return typeof result === "string" ? result : JSON.stringify(result);
      }}
    }};
    _registeredMetadata.commands[name] = true;
    hostLog("debug", "registered command as tool: " + toolName);
  }},

  // ── 8. registerGatewayMethod → mapped to tool with "kernel." prefix
  registerGatewayMethod: function(name, handler) {{
    var toolName = "kernel." + name;
    _registeredTools[toolName] = {{
      name: toolName,
      definition: {{ description: "Gateway method: " + name, inputSchema: {{ type: "object", properties: {{}} }} }},
      handler: function(id, params) {{
        var result = handler(params);
        return typeof result === "string" ? result : JSON.stringify(result);
      }}
    }};
    _registeredMetadata.gatewayMethods[name] = true;
    hostLog("debug", "registered gateway method as tool: " + toolName);
  }},

  // ── 9. registerHttpHandler (captured as metadata) ─────────────────
  registerHttpHandler: function(path, handler) {{
    _registeredMetadata.httpHandlers.push({{ path: path, handler: handler }});
    hostLog("debug", "registered http handler: " + path);
  }},

  // ── 10. registerHttpRoute (captured as metadata) ──────────────────
  registerHttpRoute: function(method, path, handler) {{
    _registeredMetadata.httpRoutes.push({{ method: method, path: path, handler: handler }});
    hostLog("debug", "registered http route: " + method + " " + path);
  }},

  // ── 11. registerProvider (captured as metadata) ───────────────────
  registerProvider: function(name, config) {{
    _registeredMetadata.providers[name] = config;
    hostLog("debug", "registered provider: " + name);
  }},

  // ── 12. registerCli (captured as metadata) ────────────────────────
  registerCli: function(name, opts) {{
    _registeredMetadata.cliCommands[name] = opts;
    hostLog("debug", "registered cli command: " + name);
  }},

  // ── 13. on (event handler) ────────────────────────────────────────
  on: function(eventName, handler) {{
    if (!_eventHandlers[eventName]) _eventHandlers[eventName] = [];
    _eventHandlers[eventName].push(handler);
  }},

  // ── Runtime helpers (minimal stubs for WASM sandbox) ──────────────
  runtime: {{
    config: {{
      loadConfig: function() {{ return _pluginConfig; }}
    }},
    channel: {{
      reply: function(channelName, message) {{
        hostLog("debug", "channel.reply to " + channelName + ": " + JSON.stringify(message));
      }}
    }}
  }}
}};

// ── Inlined plugin code (IIFE-wrapped CJS) ─────────────────────────
var _pluginModule = (function() {{
  var module = {{ exports: {{}} }};
  var exports = module.exports;"#
    )
}

/// Generate Node.js module polyfills for the WASM sandbox.
///
/// Polyfilled modules: `fs`, `path`, `os`, `buffer`, `crypto`, `url`,
/// `events`, `util`, `stream`, `http`, `https`, `querystring`.
/// Also provides `process`, `console`, and `setTimeout`/`setInterval` globals.
///
/// This is a single large string literal with no control flow — the line
/// count reflects JS template size, not Rust complexity.
#[expect(clippy::too_many_lines)]
fn generate_node_polyfills() -> &'static str {
    r#"// ── Node.js module polyfills ─────────────────────────────────────────

// ── node:fs ─────────────────────────────────────────────────────────
var _virtualFs = {
  readFileSync: function(p, opts) {
    var content = hostReadFile(String(p));
    // Always returns string — Buffer not fully supported in WASM
    return content;
  },
  writeFileSync: function(p, data, opts) {
    hostWriteFile(String(p), String(data));
  },
  appendFileSync: function(p, data) {
    var existing = "";
    try { existing = hostReadFile(String(p)); } catch(e) {}
    hostWriteFile(String(p), existing + String(data));
  },
  existsSync: function(p) {
    return hostFsExists(String(p));
  },
  mkdirSync: function(p, opts) {
    // recursive option: create parent dirs by walking up
    if (opts && opts.recursive) {
      var parts = String(p).split("/").filter(function(s) { return s !== ""; });
      var cur = p[0] === "/" ? "" : ".";
      for (var i = 0; i < parts.length; i++) {
        cur += "/" + parts[i];
        if (!hostFsExists(cur)) hostFsMkdir(cur);
      }
    } else {
      hostFsMkdir(String(p));
    }
  },
  readdirSync: function(p) {
    return hostFsReaddir(String(p));
  },
  statSync: function(p) {
    var s = hostFsStat(String(p));
    return {
      size: s.size,
      isDirectory: function() { return s.isDir; },
      isFile: function() { return !s.isDir; },
      isSymbolicLink: function() { return false; },
      mtimeMs: s.mtime * 1000,
      mtime: new Date(s.mtime * 1000)
    };
  },
  lstatSync: function(p) { return _virtualFs.statSync(p); },
  unlinkSync: function(p) {
    hostFsUnlink(String(p));
  },
  copyFileSync: function(src, dest) {
    var content = hostReadFile(String(src));
    hostWriteFile(String(dest), content);
  },
  renameSync: function(oldPath, newPath) {
    var content = hostReadFile(String(oldPath));
    hostWriteFile(String(newPath), content);
    hostFsUnlink(String(oldPath));
  },
  accessSync: function(p) {
    if (!hostFsExists(String(p))) throw new Error("ENOENT: no such file: " + p);
  },
  constants: { F_OK: 0, R_OK: 4, W_OK: 2, X_OK: 1 },
  // Stubs for stream-based APIs — not usable in sync WASM
  createReadStream: function() { throw new Error("createReadStream not supported in WASM sandbox"); },
  createWriteStream: function() { throw new Error("createWriteStream not supported in WASM sandbox"); }
};

// ── node:path ───────────────────────────────────────────────────────
var _virtualPath = {
  sep: "/",
  delimiter: ":",
  join: function() {
    var parts = [];
    for (var i = 0; i < arguments.length; i++) parts.push(arguments[i]);
    return parts.join("/").replace(/\/+/g, "/");
  },
  resolve: function() {
    var parts = [];
    for (var i = arguments.length - 1; i >= 0; i--) {
      parts.unshift(arguments[i]);
      if (arguments[i][0] === "/") break;
    }
    var joined = parts.join("/").replace(/\/+/g, "/");
    var segs = joined.split("/");
    var out = [];
    for (var j = 0; j < segs.length; j++) {
      if (segs[j] === "..") { if (out.length > 1) out.pop(); }
      else if (segs[j] !== "." && segs[j] !== "") out.push(segs[j]);
    }
    return "/" + out.join("/");
  },
  dirname: function(p) {
    var idx = p.lastIndexOf("/");
    return idx <= 0 ? "/" : p.substring(0, idx);
  },
  basename: function(p, ext) {
    var base = p.substring(p.lastIndexOf("/") + 1);
    if (ext && base.endsWith(ext)) base = base.substring(0, base.length - ext.length);
    return base;
  },
  extname: function(p) {
    var base = p.substring(p.lastIndexOf("/") + 1);
    var dot = base.lastIndexOf(".");
    return dot <= 0 ? "" : base.substring(dot);
  },
  normalize: function(p) {
    return p.replace(/\/+/g, "/").replace(/\/\.\//g, "/");
  },
  isAbsolute: function(p) {
    return p.length > 0 && p[0] === "/";
  },
  relative: function(from, to) {
    var f = _virtualPath.resolve(from).split("/");
    var t = _virtualPath.resolve(to).split("/");
    var common = 0;
    while (common < f.length && common < t.length && f[common] === t[common]) common++;
    var ups = [];
    for (var i = common; i < f.length; i++) ups.push("..");
    return ups.concat(t.slice(common)).join("/") || ".";
  },
  parse: function(p) {
    return {
      root: p[0] === "/" ? "/" : "",
      dir: _virtualPath.dirname(p),
      base: _virtualPath.basename(p),
      ext: _virtualPath.extname(p),
      name: _virtualPath.basename(p, _virtualPath.extname(p))
    };
  },
  format: function(obj) {
    var dir = obj.dir || obj.root || "";
    var base = obj.base || (obj.name || "") + (obj.ext || "");
    return dir ? dir + "/" + base : base;
  }
};
_virtualPath.posix = _virtualPath;

// ── node:os ─────────────────────────────────────────────────────────
var _virtualOs = {
  homedir: function() { return "/data"; },
  platform: function() { return "wasm"; },
  tmpdir: function() { return "/tmp"; },
  hostname: function() { return "astrid-sandbox"; },
  type: function() { return "WASM"; },
  arch: function() { return "wasm32"; },
  release: function() { return "0.0.0"; },
  cpus: function() { return [{ model: "virtual", speed: 0 }]; },
  totalmem: function() { return 268435456; },
  freemem: function() { return 134217728; },
  EOL: "\n",
  endianness: function() { return "LE"; },
  networkInterfaces: function() { return {}; },
  userInfo: function() { return { username: "astrid", homedir: "/data", shell: "/bin/sh", uid: 1000, gid: 1000 }; }
};

// ── node:buffer ─────────────────────────────────────────────────────
var _Buffer = {
  from: function(input, encoding) {
    if (typeof input === "string") {
      // Return a minimal buffer-like object
      var bytes = [];
      for (var i = 0; i < input.length; i++) bytes.push(input.charCodeAt(i) & 0xff);
      var buf = bytes;
      buf.toString = function(enc) { return input; };
      buf.length = bytes.length;
      buf.slice = function(s, e) { return _Buffer.from(input.slice(s, e)); };
      return buf;
    }
    if (Array.isArray(input)) {
      var b = input.slice();
      b.toString = function(enc) {
        var s = "";
        for (var j = 0; j < b.length; j++) s += String.fromCharCode(b[j]);
        return s;
      };
      b.length = input.length;
      return b;
    }
    return [];
  },
  alloc: function(size, fill) {
    var arr = new Array(size);
    for (var i = 0; i < size; i++) arr[i] = fill || 0;
    arr.toString = function() { return ""; };
    arr.length = size;
    return arr;
  },
  isBuffer: function(obj) {
    return Array.isArray(obj) && typeof obj.toString === "function";
  },
  concat: function(list) {
    var result = [];
    for (var i = 0; i < list.length; i++) {
      for (var j = 0; j < list[i].length; j++) result.push(list[i][j]);
    }
    result.toString = function(enc) {
      var s = "";
      for (var k = 0; k < result.length; k++) s += String.fromCharCode(result[k]);
      return s;
    };
    return result;
  },
  byteLength: function(str) { return str.length; }
};
var _virtualBuffer = { Buffer: _Buffer };

// ── node:crypto ─────────────────────────────────────────────────────
var _virtualCrypto = {
  randomUUID: function() {
    // RFC 4122 v4 UUID via Math.random (not cryptographically secure, but functional)
    var hex = "0123456789abcdef";
    var uuid = "";
    for (var i = 0; i < 36; i++) {
      if (i === 8 || i === 13 || i === 18 || i === 23) uuid += "-";
      else if (i === 14) uuid += "4";
      else if (i === 19) uuid += hex[(Math.random() * 4 | 0) + 8];
      else uuid += hex[Math.random() * 16 | 0];
    }
    return uuid;
  },
  randomBytes: function(size) {
    var bytes = [];
    for (var i = 0; i < size; i++) bytes.push(Math.floor(Math.random() * 256));
    bytes.toString = function(enc) {
      if (enc === "hex") {
        var h = "";
        for (var j = 0; j < bytes.length; j++) h += ("0" + bytes[j].toString(16)).slice(-2);
        return h;
      }
      return String.fromCharCode.apply(null, bytes);
    };
    return bytes;
  },
  createHash: function(alg) {
    // Minimal hash stub — returns a consistent hash for basic usage
    var _data = "";
    return {
      update: function(d) { _data += String(d); return this; },
      digest: function(enc) {
        // Simple DJB2 hash — NOT cryptographic, but deterministic
        var hash = 5381;
        for (var i = 0; i < _data.length; i++) hash = ((hash << 5) + hash) + _data.charCodeAt(i);
        var hex = (hash >>> 0).toString(16);
        while (hex.length < 8) hex = "0" + hex;
        if (enc === "hex") return hex;
        return hex;
      }
    };
  },
  createHmac: function(alg, key) {
    var _data = String(key);
    return {
      update: function(d) { _data += String(d); return this; },
      digest: function(enc) {
        return _virtualCrypto.createHash(alg).update(_data).digest(enc);
      }
    };
  }
};

// ── node:url ────────────────────────────────────────────────────────
var _virtualUrl = {
  URL: typeof URL !== "undefined" ? URL : function(input, base) {
    // Minimal URL polyfill
    var full = base ? base.replace(/\/$/, "") + "/" + input.replace(/^\//, "") : input;
    this.href = full;
    var match = full.match(/^(https?):\/\/([^/:]+)(:\d+)?(\/[^?#]*)(\?[^#]*)?(#.*)?$/);
    if (match) {
      this.protocol = match[1] + ":";
      this.hostname = match[2];
      this.port = match[3] ? match[3].slice(1) : "";
      this.pathname = match[4] || "/";
      this.search = match[5] || "";
      this.hash = match[6] || "";
      this.host = this.hostname + (this.port ? ":" + this.port : "");
      this.origin = this.protocol + "//" + this.host;
    }
    this.toString = function() { return this.href; };
    this.searchParams = new _URLSearchParams(this.search.slice(1));
  },
  URLSearchParams: typeof URLSearchParams !== "undefined" ? URLSearchParams : _URLSearchParams,
  parse: function(urlStr) {
    try { return new _virtualUrl.URL(urlStr); } catch(e) { return null; }
  },
  format: function(urlObj) {
    return urlObj.href || String(urlObj);
  },
  pathToFileURL: function(p) { return new _virtualUrl.URL("file://" + p); },
  fileURLToPath: function(u) {
    var s = typeof u === "string" ? u : u.href;
    return s.replace(/^file:\/\//, "");
  }
};

function _URLSearchParams(init) {
  this._params = {};
  if (typeof init === "string") {
    var pairs = init.split("&");
    for (var i = 0; i < pairs.length; i++) {
      var kv = pairs[i].split("=");
      if (kv[0]) this._params[decodeURIComponent(kv[0])] = decodeURIComponent(kv[1] || "");
    }
  }
  this.get = function(k) { return this._params[k] || null; };
  this.set = function(k, v) { this._params[k] = v; };
  this.has = function(k) { return k in this._params; };
  this.delete = function(k) { delete this._params[k]; };
  this.toString = function() {
    var parts = [];
    for (var key in this._params) parts.push(encodeURIComponent(key) + "=" + encodeURIComponent(this._params[key]));
    return parts.join("&");
  };
  this.entries = function() { return Object.entries(this._params); };
}

// ── node:events ─────────────────────────────────────────────────────
function _EventEmitter() {
  this._listeners = {};
}
_EventEmitter.prototype.on = function(event, fn) {
  if (!this._listeners[event]) this._listeners[event] = [];
  this._listeners[event].push(fn);
  return this;
};
_EventEmitter.prototype.addListener = _EventEmitter.prototype.on;
_EventEmitter.prototype.once = function(event, fn) {
  var self = this;
  var wrapper = function() {
    self.removeListener(event, wrapper);
    fn.apply(this, arguments);
  };
  return this.on(event, wrapper);
};
_EventEmitter.prototype.off = function(event, fn) {
  return this.removeListener(event, fn);
};
_EventEmitter.prototype.removeListener = function(event, fn) {
  if (!this._listeners[event]) return this;
  this._listeners[event] = this._listeners[event].filter(function(l) { return l !== fn; });
  return this;
};
_EventEmitter.prototype.removeAllListeners = function(event) {
  if (event) delete this._listeners[event];
  else this._listeners = {};
  return this;
};
_EventEmitter.prototype.emit = function(event) {
  var listeners = this._listeners[event];
  if (!listeners) return false;
  var args = Array.prototype.slice.call(arguments, 1);
  for (var i = 0; i < listeners.length; i++) listeners[i].apply(this, args);
  return true;
};
_EventEmitter.prototype.listenerCount = function(event) {
  return (this._listeners[event] || []).length;
};
_EventEmitter.prototype.listeners = function(event) {
  return (this._listeners[event] || []).slice();
};
_EventEmitter.prototype.setMaxListeners = function() { return this; };
_EventEmitter.prototype.getMaxListeners = function() { return 10; };
var _virtualEvents = { EventEmitter: _EventEmitter, default: _EventEmitter };

// ── node:util ───────────────────────────────────────────────────────
var _virtualUtil = {
  promisify: function(fn) {
    return function() {
      var args = Array.prototype.slice.call(arguments);
      return { then: function(resolve, reject) {
        args.push(function(err, result) { err ? reject(err) : resolve(result); });
        fn.apply(null, args);
      }};
    };
  },
  inspect: function(obj, opts) { return JSON.stringify(obj); },
  format: function() {
    var args = Array.prototype.slice.call(arguments);
    if (typeof args[0] !== "string") return args.map(function(a) { return String(a); }).join(" ");
    var i = 1;
    return args[0].replace(/%[sdjo%]/g, function(m) {
      if (m === "%%") return "%";
      if (i >= args.length) return m;
      return String(args[i++]);
    });
  },
  inherits: function(ctor, superCtor) {
    ctor.prototype = Object.create(superCtor.prototype);
    ctor.prototype.constructor = ctor;
  },
  deprecate: function(fn, msg) { return fn; },
  types: {
    isDate: function(v) { return v instanceof Date; },
    isRegExp: function(v) { return v instanceof RegExp; },
    isArray: function(v) { return Array.isArray(v); }
  },
  TextEncoder: typeof TextEncoder !== "undefined" ? TextEncoder : function() {
    this.encode = function(s) { return _Buffer.from(s); };
  },
  TextDecoder: typeof TextDecoder !== "undefined" ? TextDecoder : function() {
    this.decode = function(buf) { return buf.toString(); };
  }
};

// ── node:stream (stub) ──────────────────────────────────────────────
var _virtualStream = {
  Readable: _EventEmitter,
  Writable: _EventEmitter,
  Transform: _EventEmitter,
  Duplex: _EventEmitter,
  PassThrough: _EventEmitter,
  pipeline: function() { throw new Error("stream.pipeline not supported in WASM sandbox"); },
  finished: function() { throw new Error("stream.finished not supported in WASM sandbox"); }
};

// ── node:http / node:https (via host HTTP function) ─────────────────
var _virtualHttp = {
  request: function(opts, cb) {
    var url = typeof opts === "string" ? opts : (opts.protocol || "http:") + "//" + (opts.hostname || opts.host || "localhost") + (opts.port ? ":" + opts.port : "") + (opts.path || "/");
    var method = (opts.method || "GET").toUpperCase();
    var headers = opts.headers || {};
    var reqJson = JSON.stringify({ url: url, method: method, headers: headers, body: null });
    var respStr = hostHttpRequest(reqJson);
    var resp = JSON.parse(respStr);
    if (cb) cb({ statusCode: resp.status, headers: resp.headers || {},
      on: function(ev, fn) { if (ev === "data") fn(resp.body || ""); if (ev === "end") fn(); },
      setEncoding: function() {}
    });
    return { write: function(d) { /* body append */ }, end: function() {}, on: function() {} };
  },
  get: function(opts, cb) { return _virtualHttp.request(opts, cb); }
};
var _virtualHttps = _virtualHttp;

// ── node:querystring ────────────────────────────────────────────────
var _virtualQuerystring = {
  parse: function(str) {
    var obj = {};
    var pairs = (str || "").split("&");
    for (var i = 0; i < pairs.length; i++) {
      var kv = pairs[i].split("=");
      if (kv[0]) obj[decodeURIComponent(kv[0])] = decodeURIComponent(kv[1] || "");
    }
    return obj;
  },
  stringify: function(obj) {
    var parts = [];
    for (var k in obj) parts.push(encodeURIComponent(k) + "=" + encodeURIComponent(obj[k]));
    return parts.join("&");
  },
  encode: function(obj) { return _virtualQuerystring.stringify(obj); },
  decode: function(str) { return _virtualQuerystring.parse(str); }
};

// ── process global ──────────────────────────────────────────────────
var process = typeof process !== "undefined" ? process : {
  env: {},
  cwd: function() { return "."; },
  exit: function(code) { throw new Error("process.exit(" + code + ") called in WASM sandbox"); },
  platform: "wasm",
  arch: "wasm32",
  version: "v0.0.0",
  versions: {},
  argv: [],
  pid: 1,
  stdout: { write: function(s) { hostLog("info", String(s)); } },
  stderr: { write: function(s) { hostLog("error", String(s)); } },
  nextTick: function(fn) { fn(); },
  hrtime: { bigint: function() { return BigInt(Date.now()) * BigInt(1000000); } }
};

// ── console polyfill ────────────────────────────────────────────────
var console = {
  log: function() { hostLog("info", Array.prototype.slice.call(arguments).join(" ")); },
  info: function() { hostLog("info", Array.prototype.slice.call(arguments).join(" ")); },
  warn: function() { hostLog("warn", Array.prototype.slice.call(arguments).join(" ")); },
  error: function() { hostLog("error", Array.prototype.slice.call(arguments).join(" ")); },
  debug: function() { hostLog("debug", Array.prototype.slice.call(arguments).join(" ")); },
  trace: function() { hostLog("debug", Array.prototype.slice.call(arguments).join(" ")); },
  dir: function(obj) { hostLog("info", JSON.stringify(obj)); },
  assert: function(cond) { if (!cond) hostLog("error", "Assertion failed: " + Array.prototype.slice.call(arguments, 1).join(" ")); },
  time: function() {},
  timeEnd: function() {},
  timeLog: function() {}
};

// ── setTimeout / setInterval (synchronous stubs) ────────────────────
// WASM has no event loop — callbacks execute immediately (timeout ignored).
var _timerIdCounter = 1;
function setTimeout(fn, ms) { var id = _timerIdCounter++; try { fn(); } catch(e) {} return id; }
function setInterval(fn, ms) { return setTimeout(fn, ms); }
function clearTimeout(id) {}
function clearInterval(id) {}
function setImmediate(fn) { return setTimeout(fn, 0); }
function clearImmediate(id) {}
function queueMicrotask(fn) { try { fn(); } catch(e) {} }

// ── require() polyfill for Node.js modules ──────────────────────────
var _moduleCache = {};
function require(moduleName) {
  var name = moduleName.replace(/^node:/, "");
  if (_moduleCache[name]) return _moduleCache[name];
  var mod = null;
  switch(name) {
    case "fs": mod = _virtualFs; break;
    case "path": mod = _virtualPath; break;
    case "os": mod = _virtualOs; break;
    case "buffer": mod = _virtualBuffer; break;
    case "crypto": mod = _virtualCrypto; break;
    case "url": mod = _virtualUrl; break;
    case "events": mod = _virtualEvents; break;
    case "util": mod = _virtualUtil; break;
    case "stream": mod = _virtualStream; break;
    case "http": mod = _virtualHttp; break;
    case "https": mod = _virtualHttps; break;
    case "querystring": mod = _virtualQuerystring; break;
    case "assert": mod = { ok: function(v,m) { if (!v) throw new Error(m || "Assertion failed"); }, strictEqual: function(a,b,m) { if (a !== b) throw new Error(m || a + " !== " + b); } }; break;
    case "string_decoder": mod = { StringDecoder: function() { this.write = function(b) { return b.toString ? b.toString() : String(b); }; this.end = function() { return ""; }; } }; break;
    default: throw new Error("Cannot require module: " + moduleName + " (not polyfilled in WASM sandbox)");
  }
  _moduleCache[name] = mod;
  return mod;
}
require.resolve = function(name) { return name; };
require.cache = _moduleCache;

// ── Global Buffer ───────────────────────────────────────────────────
var Buffer = _Buffer;"#
}

/// Generate the Extism export functions with deferred activation.
///
/// `_ensureActivated()` is called at the top of each export function. It:
/// 1. Loads config from host (first time only)
/// 2. Calls plugin `activate()` (first time only)
#[expect(clippy::too_many_lines)]
fn generate_exports() -> String {
    r#"// ── Deferred activation (runs on first export call, NOT during Wizer init) ──
var _activated = false;

function _ensureActivated() {
  if (_activated) return;
  _activated = true;

  // Load config from host
  for (var _ci = 0; _ci < _CONFIG_KEYS.length; _ci++) {
    var _ck = _CONFIG_KEYS[_ci];
    var _cv = hostGetConfig(_ck);
    if (_cv !== undefined && _cv !== "") {
      try { _pluginConfig[_ck] = JSON.parse(_cv); }
      catch(_ce) { _pluginConfig[_ck] = _cv; }
    }
  }

  // Activate plugin
  if (typeof _pluginModule.activate === "function") {
    try {
      _pluginModule.activate(_openclawContext);
    } catch(_ae) {
      hostLog("error", "plugin activation failed: " + String(_ae));
    }
  }
}

// ── Extism exports ─────────────────────────────────────────────────
// Note: describe-tools is kept for backwards compatibility with dynamic discovery,
// but astrid_tool_call and astrid_hook_trigger are the current Inbound ABI.
module.exports["describe-tools"] = function() {
  _ensureActivated();
  var tools = [];
  var names = Object.keys(_registeredTools);
  for (var _ti = 0; _ti < names.length; _ti++) {
    var t = _registeredTools[names[_ti]];
    tools.push({
      name: t.name,
      description: t.definition.description || "",
      input_schema: JSON.stringify(t.definition.inputSchema || {})
    });
  }
  _Host.outputString(JSON.stringify(tools));
};

module.exports.astrid_tool_call = function() {
  _ensureActivated();
  var inputStr = _Host.inputString();
  var input;
  try {
    input = JSON.parse(inputStr);
  } catch(_pe) {
    _Host.outputString(JSON.stringify({
      content: "failed to parse tool input: " + String(_pe),
      is_error: true
    }));
    return;
  }

  var toolName = input.name;
  var tool = _registeredTools[toolName];
  if (!tool) {
    _Host.outputString(JSON.stringify({
      content: "unknown tool: " + toolName,
      is_error: true
    }));
    return;
  }

  var args;
  try {
    args = typeof input.arguments === "string" ? JSON.parse(input.arguments) : (input.arguments || {});
  } catch(_ae2) {
    args = {};
  }

  try {
    var result = tool.handler(toolName, args);
    // Detect unresolved Promise (QuickJS async without event loop)
    if (result && typeof result === "object" && typeof result.then === "function" && typeof result.__value === "undefined") {
      _Host.outputString(JSON.stringify({
        content: "Tool '" + toolName + "' requires async I/O which is not supported in the WASM sandbox. Use the Tier 2 MCP bridge (packages/openclaw-mcp-bridge/) instead.",
        is_error: true
      }));
      return;
    }
    var content = (typeof result === "string") ? result : JSON.stringify(result);
    _Host.outputString(JSON.stringify({
      content: content,
      is_error: false
    }));
  } catch(_ee) {
    _Host.outputString(JSON.stringify({
      content: "tool execution failed: " + String(_ee),
      is_error: true
    }));
  }
};

module.exports.astrid_hook_trigger = function() {
  _ensureActivated();
  var inputStr = _Host.inputString();
  var ctx;
  try {
    ctx = JSON.parse(inputStr);
  } catch(_pe2) {
    _Host.outputString(JSON.stringify({ action: "continue", data: null }));
    return;
  }

  var eventName = ctx.event || ctx.hook;
  var eventData = ctx.data || ctx.payload || null;
  if (typeof eventData === "string") {
    try { eventData = JSON.parse(eventData); } catch(_pd) {}
  }

  // Collect handler return values — last non-null result wins.
  // This allows interceptor hooks to modify or override data flowing
  // through the pipeline (e.g. before_prompt_build returning extra context).
  var lastResult = null;

  // Dispatch to registerHook handlers
  var hookHandlers = _registeredHooks[eventName];
  if (hookHandlers) {
    for (var _hi = 0; _hi < hookHandlers.length; _hi++) {
      try {
        var _hr = hookHandlers[_hi](eventData);
        if (_hr !== undefined && _hr !== null) { lastResult = _hr; }
      }
      catch(_he) { hostLog("error", "hook handler failed for " + eventName + ": " + String(_he)); }
    }
  }

  // Dispatch to on() event handlers
  var evHandlers = _eventHandlers[eventName];
  if (evHandlers) {
    for (var _ei = 0; _ei < evHandlers.length; _ei++) {
      try {
        var _er = evHandlers[_ei](eventData);
        if (_er !== undefined && _er !== null) { lastResult = _er; }
      }
      catch(_ee2) { hostLog("error", "event handler failed for " + eventName + ": " + String(_ee2)); }
    }
  }

  // Legacy: dispatch to module-level onEvent if present
  if (typeof _pluginModule.onEvent === "function") {
    try {
      var _lr = _pluginModule.onEvent(eventName, eventData);
      if (_lr !== undefined && _lr !== null) { lastResult = _lr; }
    } catch(_he2) {
      hostLog("error", "onEvent handler failed: " + String(_he2));
    }
  }

  _Host.outputString(JSON.stringify({ action: "continue", data: lastResult }));
};

module.exports.astrid_command_run = function() {
    _ensureActivated();
    _Host.outputString(JSON.stringify({ content: "Commands not natively supported by OpenClaw", is_error: true }));
};

module.exports.astrid_cron_trigger = function() {
    _ensureActivated();
    _Host.outputString(JSON.stringify({ content: "Cron not natively supported by OpenClaw", is_error: true }));
};

module.exports.astrid_deactivate = function() {
  if (!_activated) return;
  if (typeof _pluginModule.deactivate === "function") {
    try {
      _pluginModule.deactivate();
    } catch(_de) {
      hostLog("error", "plugin deactivation failed: " + String(_de));
    }
  }
  _activated = false;
};
"#
    .to_string()
}

/// Generate the JS array literal for config keys.
fn generate_config_keys(config: &HashMap<String, serde_json::Value>) -> String {
    if config.is_empty() {
        return String::new();
    }
    config
        .keys()
        .map(|k| format!("\"{}\"", escape_js_string(k)))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Escape a string for use in a JS string literal.
fn escape_js_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_identity() -> PluginIdentity<'static> {
        PluginIdentity {
            id: "test-plugin",
            name: Some("Test Plugin"),
            version: Some("1.0.0"),
            description: Some("A test plugin"),
        }
    }

    #[test]
    fn shim_contains_exports() {
        let config = HashMap::new();
        let shim = generate("// plugin code", &config, &test_identity());
        assert!(shim.contains("describe-tools"));
        assert!(shim.contains("astrid_tool_call"));
        assert!(shim.contains("astrid_hook_trigger"));
    }

    #[test]
    fn shim_contains_plugin_code() {
        let config = HashMap::new();
        let shim = generate("console.log('hello');", &config, &test_identity());
        assert!(shim.contains("console.log('hello');"));
        assert!(shim.contains("BEGIN PLUGIN CODE"));
        assert!(shim.contains("END PLUGIN CODE"));
    }

    #[test]
    fn shim_bakes_config_keys() {
        let mut config = HashMap::new();
        config.insert("apiKey".into(), serde_json::json!("sk-123"));
        config.insert("timeout".into(), serde_json::json!(30));
        let shim = generate("// code", &config, &test_identity());
        assert!(shim.contains("\"apiKey\""));
        assert!(shim.contains("\"timeout\""));
    }

    #[test]
    fn shim_empty_config() {
        let config = HashMap::new();
        let shim = generate("// code", &config, &test_identity());
        assert!(shim.contains("var _CONFIG_KEYS = [];"));
    }

    #[test]
    fn shim_has_host_function_wrappers() {
        let config = HashMap::new();
        let shim = generate("// code", &config, &test_identity());
        assert!(shim.contains("function hostLog("));
        assert!(shim.contains("function hostGetConfig("));
        assert!(shim.contains("function hostReadFile("));
        assert!(shim.contains("function hostWriteFile("));
        assert!(shim.contains("function hostKvGet("));
        assert!(shim.contains("function hostKvSet("));
        assert!(shim.contains("function hostHttpRequest("));
        assert!(shim.contains("function hostFsExists("));
        assert!(shim.contains("function hostFsMkdir("));
        assert!(shim.contains("function hostFsReaddir("));
        assert!(shim.contains("function hostFsStat("));
        assert!(shim.contains("function hostFsUnlink("));
    }

    #[test]
    fn shim_has_node_polyfills() {
        let config = HashMap::new();
        let shim = generate("// code", &config, &test_identity());
        // Core modules
        assert!(shim.contains("_virtualFs"), "missing fs polyfill");
        assert!(shim.contains("_virtualPath"), "missing path polyfill");
        assert!(shim.contains("_virtualOs"), "missing os polyfill");
        // Extended modules
        assert!(shim.contains("_Buffer"), "missing Buffer polyfill");
        assert!(shim.contains("_virtualCrypto"), "missing crypto polyfill");
        assert!(shim.contains("_virtualUrl"), "missing url polyfill");
        assert!(shim.contains("_EventEmitter"), "missing events polyfill");
        assert!(shim.contains("_virtualUtil"), "missing util polyfill");
        assert!(shim.contains("_virtualStream"), "missing stream polyfill");
        assert!(shim.contains("_virtualHttp"), "missing http polyfill");
        assert!(
            shim.contains("_virtualQuerystring"),
            "missing querystring polyfill"
        );
        // Globals
        assert!(shim.contains("function require("), "missing require");
        assert!(shim.contains("require.resolve"), "missing require.resolve");
        assert!(shim.contains("require.cache"), "missing require.cache");
        assert!(shim.contains("function setTimeout"), "missing setTimeout");
        assert!(shim.contains("var console ="), "missing console polyfill");
        assert!(shim.contains("var process ="), "missing process polyfill");
        assert!(
            shim.contains("var Buffer = _Buffer"),
            "missing global Buffer"
        );
    }

    #[test]
    fn shim_has_plugin_context_with_all_registrations() {
        let config = HashMap::new();
        let shim = generate("// code", &config, &test_identity());
        // Context object exists
        assert!(shim.contains("_openclawContext"), "missing context object");
        assert!(shim.contains("_pluginConfig"), "missing pluginConfig");
        // Plugin identity
        assert!(shim.contains("id: \"test-plugin\""), "missing plugin id");
        assert!(shim.contains("source: \"wasm\""), "missing source field");
        // All 13 registration methods
        assert!(shim.contains("registerTool:"), "missing registerTool");
        assert!(shim.contains("registerService:"), "missing registerService");
        assert!(shim.contains("registerChannel:"), "missing registerChannel");
        assert!(shim.contains("registerHook:"), "missing registerHook");
        assert!(shim.contains("registerCommand:"), "missing registerCommand");
        assert!(
            shim.contains("registerGatewayMethod:"),
            "missing registerGatewayMethod"
        );
        assert!(
            shim.contains("registerHttpHandler:"),
            "missing registerHttpHandler"
        );
        assert!(
            shim.contains("registerHttpRoute:"),
            "missing registerHttpRoute"
        );
        assert!(
            shim.contains("registerProvider:"),
            "missing registerProvider"
        );
        assert!(shim.contains("registerCli:"), "missing registerCli");
        assert!(shim.contains("on:"), "missing on (event handler)");
        // Helpers
        assert!(shim.contains("resolvePath:"), "missing resolvePath");
        assert!(shim.contains("pluginConfig:"), "missing pluginConfig alias");
        assert!(shim.contains("runtime:"), "missing runtime object");
    }

    #[test]
    fn shim_has_hook_and_event_registries() {
        let config = HashMap::new();
        let shim = generate("// code", &config, &test_identity());
        assert!(
            shim.contains("var _registeredHooks = {}"),
            "missing hook registry"
        );
        assert!(
            shim.contains("var _eventHandlers = {}"),
            "missing event handler registry"
        );
        assert!(
            shim.contains("var _registeredServices = {}"),
            "missing service registry"
        );
        assert!(
            shim.contains("var _registeredChannels = {}"),
            "missing channel registry"
        );
    }

    #[test]
    fn shim_hook_trigger_dispatches_to_registries() {
        let config = HashMap::new();
        let shim = generate("// code", &config, &test_identity());
        // Hook trigger should dispatch to _registeredHooks and _eventHandlers
        assert!(
            shim.contains("hookHandlers = _registeredHooks[eventName]"),
            "hook trigger should dispatch to registered hooks"
        );
        assert!(
            shim.contains("evHandlers = _eventHandlers[eventName]"),
            "hook trigger should dispatch to event handlers"
        );
    }

    #[test]
    fn shim_identity_with_no_optionals() {
        let config = HashMap::new();
        let identity = PluginIdentity {
            id: "bare-plugin",
            name: None,
            version: None,
            description: None,
        };
        let shim = generate("// code", &config, &identity);
        assert!(shim.contains("id: \"bare-plugin\""));
        assert!(shim.contains("name: null"));
        assert!(shim.contains("version: \"0.0.0\""));
        assert!(shim.contains("description: null"));
    }

    #[test]
    fn shim_wraps_code_in_iife() {
        let config = HashMap::new();
        let shim = generate("var x = 42;", &config, &test_identity());
        assert!(shim.contains("var _pluginModule = (function()"));
        assert!(shim.contains("var module = { exports: {} };"));
        assert!(shim.contains("return module.exports.default || module.exports;"));
    }

    #[test]
    fn shim_has_deferred_activation() {
        let config = HashMap::new();
        let shim = generate("// code", &config, &test_identity());
        assert!(
            shim.contains("_ensureActivated()"),
            "should have lazy activation"
        );
        assert!(
            shim.contains("var _activated = false"),
            "should track activation state"
        );
    }

    #[test]
    fn escape_js_string_basics() {
        assert_eq!(escape_js_string("hello"), "hello");
        assert_eq!(escape_js_string("he\"llo"), "he\\\"llo");
        assert_eq!(escape_js_string("a\\b"), "a\\\\b");
        assert_eq!(escape_js_string("a\nb"), "a\\nb");
    }
}
